### ISSUE TITLE
Unable to run gabutdm snap on Ubuntu

### ISSUE THREAD

**Issue by manikandancode** [gabutakut/gabutdm#129]
OS: Ubuntu 21.10 Wayland

![Screenshot from 2022-02-25 13-01-21](https://user-images.githubusercontent.com/46480489/156309132-955c68d2-0521-45e8-8c5d-5b19b5aa503e.png)

**Comment by torikulhabib** [comment]
New version with Gtk4 and Libsoup3.0

**Comment by manikandancode** [comment]
Still not fixed. 
Ubuntu 22.04 Wayland
gabutdm 1.6.5
![Screenshot from 2022-07-14 13-58-48](https://user-images.githubusercontent.com/46480489/178981302-f59f7ad7-8221-40d1-b3f6-657eb608a701.png)
