### ISSUE TITLE
[Feature Request] Download Acceleration

### ISSUE THREAD

**Issue by Dansito** [gabutakut/gabutdm#130]
Hello, I have had the opportunity to try your program and it is quite good, I would like to know if you have the possibility of adding the function to accelerate downloads, if you have ever tried similar programs such as (IDM) for windows or FDM, you will know that they they somehow maximize download speed on files. I would love that feature in this app.

**Comment by torikulhabib** [comment]
Actually I have a plan for a custom aria2 for peat, it might take some time and wait.

**Comment by tazihad** [comment]
IDM splits downloads I think aria2 also supports this feature.

**Comment by torikulhabib** [comment]
https://github.com/gabutakut/gabutdm/commit/2818035f882580c9385fe3b5b56c95024b9e2f74
