### ISSUE TITLE
[Request] use of libadwaita?

### ISSUE THREAD

**Issue by Radical4ever** [gabutakut/gabutdm#156]
Hi, this is one of my favorite apps i use on every os i install in my pc. Now that is already ported to gtk4, is it possible to be ported to libadwaita for better look in gnome?. Thank you

**Comment by torikulhabib** [comment]
if using libadwaita A lot of code changed.

**Comment by torikulhabib** [comment]
if using libadwaita A lot of code changed.

**Comment by Romchec** [comment]
Please no...

**Comment by Radical4ever** [comment]
i opened the issue bc on first dark mode isnt working and second i cant customize the app, i managed to make gtk4 apps(that dont use libadwaita style) to use it and the only one who doesnt follow this is this one. so any suggestion or solution to that?
