### ISSUE TITLE
can't download it on google driver

### ISSUE THREAD

**Issue by dandidwi** [gabutakut/gabutdm#187]
Can't download on Google Drive.The Google Driver link that I downloaded https://drive.google.com/file/d/1_BNNV6I-Ko26xHIt9_7JE5e06mh_7z6Q/view?confirm=t

**Comment by torikulhabib** [comment]
Ok. Q perbaiki segera ✈️

**Comment by torikulhabib** [comment]
https://github.com/gabutakut/gabutdm/pull/188
