### ISSUE TITLE
Aplikasi yang ditampilkan erorr

### ISSUE THREAD

**Issue by dandidwi** [gabutakut/gabutdm#194]
aplikasi yang ditampilkan tidak seperti di gnome banyak icon yang gak muncul, desktop yang saya gunakan kde plasma distro fedore kinoite dan flatpak

![Screenshot_20220920_205841](https://user-images.githubusercontent.com/32098025/191278866-1310a222-e390-47dc-8565-f045fdd465e7.png)

**Comment by torikulhabib** [comment]
install icon pack untuk flatpack

**Comment by dandidwi** [comment]
sudah solved, ternyata harus diubah ke dark mode mengikuti tema kde

**Comment by dandidwi** [comment]
sudah solved, ternyata harus diubah ke dark mode mengikuti tema kde
