### ISSUE TITLE
Possible UI improvements

### ISSUE THREAD

**Issue by VarLad** [gabutakut/gabutdm#206]
Here's a list of UI improvements I think would be better for GabutDM

1. Having these options on right click on the download instead of bottom left 
![image](https://user-images.githubusercontent.com/51269425/201490243-8c02fab7-fed0-471d-ba00-175a4c4b22d9.png)

While having them in the bottom left would be useful on phones or small screens, I believe its weird for desktops or large screens. 

2. Provide "Connection" "Split" "Split Size" "Number of Tries" per download along with the existing global settings. Make the global settings the default while they can be tweaked per download.
![image](https://user-images.githubusercontent.com/51269425/201490350-b6ca462d-ab18-4daf-ba64-85c3e1784628.png)

3. Merge Folder and Address menus. Remember the last folder selection for the next download until Gabut is closed. Its annoying to pick a folder everytime if you're downloading into the same folder everytime
![image](https://user-images.githubusercontent.com/51269425/201490422-229a149c-3276-42b3-aba5-810b5314c190.png)

3. (alt.) An alternative to the above is, if possible, allow giving multiple URLs and multiple filenames in Gabut. That would justify having another bar for Folder. Possibly an add button for adding links and filenames

@torikulhabib Let me know your opinion on this whenever you get time :smiley:

**Comment by torikulhabib** [comment]
1. each side has a button, right click is too common
2. reload settings for each download
3. I will put the folder settings next to the url to make it easier to select saved folders - worth doing
4. many url seems very strange

**Comment by torikulhabib** [comment]
https://github.com/gabutakut/gabutdm/pull/208
