### ISSUE TITLE
Support Youtube downloading

### ISSUE THREAD

**Issue by tazihad** [gabutakut/gabutdm#215]
Please support youtube downloading using `yt-dlp`& `youtube-dl`. 

**Requested features:**
1. Support youtube downloads.
2. Option to select download video quality. Either in extension or in download manager.
3. Download option should have audio and video both in different quality and format. [TheFrenchGhosty](https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection) has some good scripts to download different quality videos.

**Comment by torikulhabib** [comment]
https://github.com/gabutakut/gabutextentionsGC

**Comment by tazihad** [comment]
@torikulhabib I tried downloading youtube video. But it only downloads video. no audio. Any solution?

**Comment by torikulhabib** [comment]
Actually, you have to download video and audio and then merge them with ffmpeg. or maybe i will make a new application tool for gui from ffmpeg which is simple and easy to use.

**Comment by torikulhabib** [comment]
for the video quality will follow the player browser
