### ISSUE TITLE
[Feature Request] Wayland Support

### ISSUE THREAD

**Issue by rickyrsyah** [gabutakut/gabutdm#216]

**Comment by torikulhabib** [comment]
anehnya saya jalankan tanpa sandbox bisa.

![Screenshot from 2023-01-25 15-47-21](https://user-images.githubusercontent.com/26135527/214533350-133eb041-6d87-4fb9-b460-db6b08e596ef.png)

mungkin ada sesuatu yang salah pada konfig yang saya buat untuk flatpack.
aku akan mencoba yang rebaik.

**Comment by torikulhabib** [comment]
https://github.com/flathub/com.github.gabutakut.gabutdm/pull/10
