### ISSUE TITLE
dark mode doesn't work on gnome wayland

### ISSUE THREAD

**Issue by dandidwi** [gabutakut/gabutdm#220]
warna dark mode gak sesuai di desktop gnome wayland bang, saya memakai versi flatpak
[Screencast from 2023-02-08 07-02-23.webm](https://user-images.githubusercontent.com/32098025/217394995-173f4b8d-b224-4774-8340-d00d07d9282c.webm)

**Comment by torikulhabib** [comment]
https://github.com/gabutakut/gabutdm/pull/236
