### ISSUE TITLE
GabutDM in Snapd : Segmentation Fault error

### ISSUE THREAD

**Issue by Anifyuli** [gabutakut/gabutdm#224]
Hello. I have problem after installing GabutDM on Snapd Ubuntu 22.10. After install and launch it, GabutDM give output (I launch it from terminal) segmentation fault error. Please solve this problem. Thanks for read my issue and fix this problem

**Comment by torikulhabib** [comment]
saya masih menunggu snap rilis versi 1.7 setelah itu baru saya perbaiki...

**Comment by Anifyuli** [comment]
Baiklah, ditunggu kabar baiknya
