### ISSUE TITLE
Upgrade to GNOME 44 Runtime?

### ISSUE THREAD

**Issue by ThunderbyteCH** [gabutakut/gabutdm#228]
"Info: runtime org.gnome.Platform branch 42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.github.gabutakut.gabutdm"

**Comment by torikulhabib** [comment]
https://github.com/flathub/com.github.gabutakut.gabutdm/pull/8
