### ISSUE TITLE
Breeze theme not working 

### ISSUE THREAD

**Issue by tazihad** [gabutakut/gabutdm#241]
Breeze theme from custom not working in KDE plasma from new release. Setting it doesn't change anything.

**Comment by torikulhabib** [comment]
make sure the gtk4 breeze theme is installed

**Comment by tazihad** [comment]
@torikulhabib how do I install gtk4 breeze theme? I can't find it.

**Comment by torikulhabib** [comment]
https://launchpad.net/~torik-habib/+archive/ubuntu/gabutdownloadmanager
