### ISSUE TITLE
[Feature Request] Tooltips and/or Documentations

### ISSUE THREAD

**Issue by curable-online** [gabutakut/gabutdm#244]
The software is very advanced and capable by itself; even pretty customisable & configurable as well.

But this, in return, can bring confusion for an user, specially when dealing with settings window and settings options.   
Nevertheless, there's no documentation for options and capabilities of GabutDM. — Or at least I can't find any.

I wish if it had a Tooltip for each option in the settings explaining what does that option exactly.

Or some kind of Help option or a kind of wiki.

**Comment by torikulhabib** [comment]
Ok i will fix soon

**Comment by torikulhabib** [comment]
https://github.com/gabutakut/gabutdm/pull/263
