### ISSUE TITLE
[FR] Add "Exit" button to tray Icon, Edge/chromium integration and more

### ISSUE THREAD

**Issue by nimbold** [gabutakut/gabutdm#249]
First of all thanks a lot for this amazing software!
I have two main feature requests that thought you might consider:
- Adding an "**Exit**" button to the tray Icon (can't exit the app without killing it)
- Adding an **Edge/chromium-based** extension to support integration.

an extra feature request:
- Creating subfolders and assigning the downloads to save in the correct sub folder.  For example: If the downloaded file is (.zip) it automatically saves it in the **main_download_folder/Compressed/**

**Comment by torikulhabib** [comment]
https://github.com/gabutakut/gabutextentionsFF/commit/f346f975051b6c872a3b5993a5f2d4325d1b143c
