### ISSUE TITLE
Consider additional categories

### ISSUE THREAD

**Issue by danrabbit** [gabutakut/gabutdm#25]
https://github.com/gabutakut/gabutdm/blob/9ba68754f640a5289b5d5034007491ba270a9d59/data/com.github.gabutakut.gabutdm.desktop.in#L9

From https://specifications.freedesktop.org/menu-spec/latest/apas02.html

`P2P` and `FileTransfer` probably apply here

**Comment by torikulhabib** [comment]
https://github.com/gabutakut/gabutdm/pull/28
