### ISSUE TITLE
[Flatpak] Update GNOME runtime

### ISSUE THREAD

**Issue by jhpgcj** [gabutakut/gabutdm#254]
Hello!

Whenever I update my flatpaks through command line, there's the following warning message:

> The GNOME 44 runtime is no longer supported as of March 20, 2024. Please ask your application developer to migrate to a supported platform.

Then, it lists Gabut DM as the application still using it.

Thanks for your attention!

**Comment by torikulhabib** [comment]
https://github.com/flathub/com.github.gabutakut.gabutdm/pull/19
