### ISSUE TITLE
Custom colors don't pass contrast check

### ISSUE THREAD

**Issue by danrabbit** [gabutakut/gabutdm#26]
https://github.com/gabutakut/gabutdm/blob/9ba68754f640a5289b5d5034007491ba270a9d59/data/com.github.gabutakut.gabutdm.appdata.xml.in#L96

Currently, custom colors in Appdata are below minimum acceptable contrast:
![Screenshot from 2021-12-01 18 31 24](https://user-images.githubusercontent.com/7277719/144346721-6853bfe5-1b30-47f0-9843-2637c4a0038a.png)

I would suggest changing your background color to `#2A7D00` to meet AA level:

![Screenshot from 2021-12-01 18 32 55](https://user-images.githubusercontent.com/7277719/144346891-587dd8d0-98b8-4a17-b341-b1bba95308af.png)

**Comment by torikulhabib** [comment]
https://github.com/gabutakut/gabutdm/pull/28
