### ISSUE TITLE
Menyapa 

### ISSUE THREAD

**Issue by knightazura** [gabutakut/gabutdm#29]
Halo bro,

Mantap, keren nih appnya! Pertama liat di AppStore yg kebayang pertama kali pasti developernya ini orang Indonesia :smile: 
Oiya kalau mau kontribusi bisa ngga bro? Ane baru belajar buat destkop app juga sih hehe

Thanks yo buat appnya!

**Comment by torikulhabib** [comment]
Makasih Bro.
Silahkan.
Mantap.
dan sama sama bro.
