### ISSUE TITLE
Window corners and window control

### ISSUE THREAD

**Issue by fayjie92** [gabutakut/gabutdm#42]
First of all, thank you very much for giving us such a wonderful download manager. 

### Issue:
1. The bottom window corners are not rounded (even though it applies rounded corners).
2. The window controls does not follow the system window control setting.

### Visualization:
![issues](https://user-images.githubusercontent.com/32283602/145746947-b748111e-7b4f-431d-9102-462c37500695.png)

### Reference:
https://github.com/elementary/tasks/issues/273

**Comment by torikulhabib** [comment]
I will fix soon

**Comment by torikulhabib** [comment]
https://github.com/gabutakut/gabutdm/pull/43
