### ISSUE TITLE
Unable to run gabutdm flatpak on Ubuntu

### ISSUE THREAD

**Issue by manikandancode** [gabutakut/gabutdm#54]
OS: Ubuntu 21.10 Wayland

![Screenshot from 2021-12-18 16-13-56](https://user-images.githubusercontent.com/46480489/146640747-40e62a4e-bbed-4c4d-bb0b-450bbe8f0063.png)

**Comment by torikulhabib** [comment]
i will fix soon.

**Comment by torikulhabib** [comment]
I think this issue not on my app just settings of flatpak
can you try this.
sudo flatpak override --nosocket=wayland com.github.gabutakut.gabutdm

**Comment by manikandancode** [comment]
Working after "sudo flatpak override --nosocket=wayland com.github.gabutakut.gabutdm"

**Comment by funcelot** [comment]
> sudo flatpak override --nosocket=wayland com.github.gabutakut.gabutdm

I tied to fight and just got installed Transmission, and happy with it, which serves me on Apple, Windows and Linux for years...
