### ISSUE TITLE
Speed Limiter should be in Kilobyte

### ISSUE THREAD

**Issue by jawadalkassim** [gabutakut/gabutdm#57]
![image](https://user-images.githubusercontent.com/48631694/146690333-1155ca51-40a5-4e55-a59d-c08b704a9588.png)

All Download Managers use Kilobyte in speed limiter option not in Bytes, it's easier to use

**Comment by torikulhabib** [comment]
Ok.
i will change it soon.

**Comment by torikulhabib** [comment]
https://github.com/gabutakut/gabutdm/pull/62
