### ISSUE TITLE
New name & Icon for the app!

### ISSUE THREAD

**Issue by wada3n** [gabutakut/gabutdm#58]
First of all, I would like to thank you for this wonderful work.
Honestly, I've been hoping for a long time that Linux has a worthy download manager.
This app does literally everything.

I think the name does not match the GNOME Human Interface Guidelines, So I think changing the name will make the app brighter.
I personally suggest:

**- Parachute**
**- Landing**
**- Droneload**

The name "Droneload" is derived from Drones and Downloads. I have been working on a download manager project for a long time, but unfortunately I could not finish it.
I think it's kind of innovative, and this App that you developed is way better than I could have come up with.

**Comment by torikulhabib** [comment]
Thank for suggest. :+1:
