### ISSUE TITLE
Unable to run gabutdm snap on Ubuntu

### ISSUE THREAD

**Issue by manikandancode** [gabutakut/gabutdm#69]
OS: Ubuntu 21.10 Wayland

![gabutdm](https://user-images.githubusercontent.com/46480489/147382368-968a0762-8582-46fd-bddd-f765e71eb886.png)

**Comment by torikulhabib** [comment]
Thanks,
i will fix soon

**Comment by torikulhabib** [comment]
fixed
https://github.com/gabutakut/gabutdm/pull/84
